#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.3f1_f880dceab6fe"
#define UNITY_VERSION_FULL_NICE "2019.4.3f1 (f880dceab6fe)"
#define UNITY_VERSION_BLD 16285916
#define UNITY_VERSION_DATE 1593766793
#define UNITY_VERSION_WIN "2019.4.3.16285916"
#define UNITY_VERSION_BRANCH "2019.4/release"
