namespace OpenTK.Platform.MacOS.Carbon
{
    internal enum OSStatus
    {
        NoError = 0,
        ParameterError = -50,
        NoHardwareError = -200,
        NotEnoughHardwareError = -201,
        UserCanceledError = -128,
        QueueError = -1,
        VTypErr = -2,
        CorErr = -3,
        UnimpErr = -4,
        SlpTypeErr = -5,
        SeNoDB = -8,
        ControlErr = -17,
        StatusErr = -18,
        ReadErr = -19,
        WritErr = -20,
        BadUnitErr = -21,
        UnitEmptyErr = -22,
        OpenErr = -23,
        ClosErr = -24,
        DRemovErr = -25,
        DInstErr = -26,
        InvalidWindowPtr = -5600,
        UnsupportedWindowAttributesForClass = -5601,
        WindowDoesNotHaveProxy = -5602,
        WindowPropertyNotFound = -5604,
        UnrecognizedWindowClass = -5605,
        CorruptWindowDescription = -5606,
        UserWantsToDragWindow = -5607,
        WindowsAlreadyInitialized = -5608,
        FloatingWindowsNotInitialized = -5609,
        WindowNotFound = -5610,
        WindowDoesNotFitOnscreen = -5611,
        WindowAttributeImmutable = -5612,
        WindowAttributesConflict = -5613,
        WindowManagerInternalError = -5614,
        WindowWrongState = -5615,
        WindowGroupInvalid = -5616,
        WindowAppModalStateAlreadyExists = -5617,
        WindowNoAppModalState = -5618,
        WindowDoesntSupportFocus = -30583,
        WindowRegionCodeInvalid = -30593,
        EventAlreadyPosted = -9860,
        EventTargetBusy = -9861,
        EventDeferAccessibilityEvent = -9865,
        EventInternalError = -9868,
        EventParameterNotFound = -9870,
        EventNotHandled = -9874,
        EventLoopTimedOut = -9875,
        EventLoopQuit = -9876,
        EventNotInQueue = -9877,
        HotKeyExists = -9878,
        EventPassToNextTarget = -9880
    }
}

